---
#lec13_CircleCI/.ansible/roles/03_rails/tasks/main.yml
- name: Install Rails
  shell: bash -lc "gem install rails -v {{ rails_version }} --no-document"
  register: rails_install
  changed_when: "'Successfully installed' in rails_install.stdout"
