---
#lec13_CircleCI/.ansible/roles/03_rails/tasks/main.yml

- name: Check if Rails is installed
  command: /home/ec2-user/.rbenv/shims/gem list rails -i
  register: rails_installed
  ignore_errors: yes

- name: Install Rails if not installed
  shell: bash -lc "gem install rails -v {{ rails_version }} --no-document"
  when: rails_installed.stdout != "true"
