---
#ローカルからS3へ変更
- name: set development.rb
  template:
    src: development.rb.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/environments/development.rb

#S3の設定
- name: set S3 storage.yml
  template:
    src: storage.yml.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/storage.yml
  ignore_errors: yes

#libvipsのインストール
- name: Install Python3 and pip
  yum:
    name:
      - python3
      - python3-pip
    state: present
  become: yes  #システム全体で使えるように

- name: Install ninja-build
  yum:
    name: ninja-build
    state: present
  become: yes

- name: Install Meson and Ninja using pip
  shell: bash -lc "pip3 install meson ninja"
  ignore_errors: yes

- name: Add Meson to PATH in .bashrc
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present

- name: Source .bashrc to update PATH
  shell: source /home/ec2-user/.bashrc
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Clone libvips repository
  git:
    repo: https://github.com/libvips/libvips.git
    dest: /home/ec2-user/libvips
    update: no

- name: Compile libvips
  shell: bash -lc "meson setup build --prefix=/home/ec2-user/.local"
  args:
    chdir: /home/ec2-user/libvips
  ignore_errors: yes

- name: Build libvips
  shell: bash -lc "meson compile"
  args:
    chdir: /home/ec2-user/libvips/build
  ignore_errors: yes

- name: meson test
  shell: bash -lc "meson test"
  args:
    chdir: /home/ec2-user/libvips/build
  ignore_errors: yes

- name: install libvips
  shell: bash -lc "meson install"
  args:
    chdir: /home/ec2-user/libvips/build
  become: yes 
  ignore_errors: yes


#実行準備
- name: Run bundle install
  shell: |
    bash -lc "bundle install"
  args: 
    chdir: "{{ app_dir }}"
  ignore_errors: yes

- name: 'asset precompile'
  shell: |
    bash -lc "rails assets:precompile"
  args: 
    chdir: "{{ app_dir }}"
  ignore_errors: yes

- name: Create database if it does not exist
  ansible.builtin.command: bundle exec rake db:create
  args:
    chdir: "{{ app_dir }}"
  become: yes
  ignore_errors: yes

- name: Run database migration
  ansible.builtin.command: bundle exec rake db:migrate
  args:
    chdir: "{{ app_dir }}"
  become: yes
  ignore_errors: yes

- name: 'bin/setup'
  shell: |
    bash -lc "bin/setup"
  args: 
    chdir: "{{ app_dir }}"
  ignore_errors: yes