---
- name: Run bundle install
  shell: |
    bash -lc "bundle install"
  args: 
    chdir: "{{ app_dir }}"
  ignore_errors: yes

#ローカルからS3へ変更
- name: set development.rb
  template:
    src: development.rb.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/environments/development.rb
#S3の設定
- name: set S3 storage.yml
  template:
    src: storage.yml.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/storage.yml
  ignore_errors: yes

#libvipsのインストール
- name: Install Python3 and pip
  yum:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Meson using pip
  pip:
    name:
      - meson
    state: present
    executable: /usr/bin/pip3

- name: Clone libvips repository
  git:
    repo: https://github.com/libvips/libvips.git
    dest: /home/ec2-user/libvips
    update: no

- name: Compile libvips
  shell: bash -lc "meson setup build --prefix /usr/.local/bin"
  args:
    chdir: /home/ec2-user/libvips
  ignore_errors: yes

- name: Build libvips
  shell: bash -lc "meson compile"
  args:
    chdir: /home/ec2-user/libvips/build
  ignore_errors: yes

- name: meson test
  shell: bash -lc "meson test"
  args:
    chdir: /home/ec2-user/libvips/build
  ignore_errors: yes

- name: install libvips
  shell: bash -lc "meson install"
  args:
    chdir: /home/ec2-user/libvips/build
  ignore_errors: yes

