---
- name: Clone Yarn repository
  git:
    repo: https://github.com/yarnpkg/yarn.git
    dest: /home/ec2-user/yarn
    version: "v1.22.19" 

- name: Create yarn directory
  file:
    path: /home/ec2-user/yarn
    state: directory
  become: yes
  become_user: ec2-user

- name: Add Yarn to PATH in .bash_profile
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="/home/ec2-user/yarn/bin:$PATH"'
    state: present
  become: yes

- name: Reload .bash_profile
  shell: source /home/ec2-user/.bash_profile
  args:
    executable: /bin/bash
