version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.2.3
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.1.4

jobs:
  cfn-lint:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: Run cfn-lint for CloudFormation
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  execute-cloudformation:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION

      - run:
          name: Deploy to AWS from template
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/2_RDS_S3.yml \
              --stack-name Lec13-RDS 
      - run:
          name: Get RDS Endpoint
          command: |
            RDS_ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier lec13-target-rds --query "DBInstances[*].Endpoint.Address" --output text --region ap-northeast-1)
            echo "RDS_ENDPOINT=${RDS_ENDPOINT}" >> $BASH_ENV
            echo "RDS_ENDPOINT is set to ${RDS_ENDPOINT}"

  execute-ansible:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:GGnZbMk8Sh2fjRjHpTcrTyZxFL+28kescRq098wu4Zs"
      - ansible-playbook/install:
          version: 2.9.27
      - run:
          name: Run Ansible Playbook
          command: |
            ansible-playbook -i /home/ec2-user/lec13_CircleCI/.ansible/inventory.ini /home/ec2-user/lec13_CircleCI/.ansible/playbook.yml -vvv --extra-vars "rds_endpoint=${RDS_ENDPOINT} ssh_private_key_path=/home/circleci/.ssh/id_rsa""

  test-serverspec:
    docker:
      - image: ruby:3.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install rspec
            gem install serverspec

      - run:
          name: Run Serverspec tests
          command: |
            cd serverspec/spec/target-node
            rspec lec13_spec.rb

workflows:
  workflow:
    jobs:
      - cfn-lint
      - execute-cloudformation:
          requires:
            - cfn-lint
      - execute-ansible:
          requires:
            - execute-cloudformation
      - test-serverspec:
          requires:
            - execute-ansible
