version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.2.3
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.1.4

jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy to AWS from template #既存のVPC上にEC2やRDSなどを構築
          command: |
            set -x
            aws cloudformation deploy \
              --template-file cloudformation/1_EC2_ALB.yml \
              --stack-name Lec13-EC2 \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides MyKeyPair=${MY_KEY_PAIR} MyIP=${MY_IP}
            aws cloudformation deploy \
              --template-file cloudformation/2_RDS_S3.yml \
              --stack-name Lec13-RDS
              
workflows:
  workflow:
    jobs:
      - execute-cloudformation
