version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.2.3
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.1.4

jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy to AWS from template #既存のVPC上にEC2やRDSなどを構築、EIPは既存のものを使用
          command: |
            set -x
            aws cloudformation deploy \
              --template-file cloudformation/1_EC2_ALB.yml \
              --stack-name Lec13-EC2 \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides MyKeyPair=${MY_KEY_PAIR} MyIP=${MY_IP} ExistingElasticIP=${EIP_ADDRESS}
            aws cloudformation deploy \
              --template-file cloudformation/2_RDS_S3.yml \
              --stack-name Lec13-RDS

  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:QX4v5d9se4rjHsQdGBJjYGdFDVKDACcThQSM2bkvVb8"
      - run:
        name: Start SSH Agent and Add Key
        command: |
          eval $(ssh-agent -s)
          ssh-add /home/ec2-user/.ssh/id_rsa
      - run:
          name: Ensure known_hosts file exists
          command: |
            touch ~/.ssh/known_hosts
      - ansible-playbook/install:
          version: 2.10.7
      - ansible-playbook/playbook:
          playbook: .ansible/playbook.yml
          playbook-options: -u ec2-user -i .ansible/inventory.ini --private-key /home/ec2-user/.ssh/id_rsa -e "ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
          
          playbook: .ansible/playbook.yml
          playbook-options: -u ec2-user -i .ansible/inventory.ini --private-key /home/ec2-user/.ssh/id_rsa -e "ansible_ssh_extra_args='-o StrictHostKeyChecking=no' -e 'RDS_PASSWORD=${RDS_PASSWORD}'"
          
workflows:
  workflow:
    jobs:
      - execute-cloudformation
      - execute-ansible:
          requires:
            - execute-cloudformation
