---
- hosts: all
  user: ec2-user 
  become: yes

  roles:
    - { role: 01_setup }
    - { role: 02_ruby }
    - { role: 03_rails }
    - { role: 04_nodejs }
    - { role: 05_yarn }
    - { role: 06_mysql }
    - { role: 07_app_dev }
