---
- hosts: target_ec2
  user: ec2-user 

  roles:
    - { role: 01_clone }
    - { role: 02_ruby }
    - { role: 03_bundler }
    - { role: 04_rails }
    - { role: 05_nodejs }
    - { role: 06_yarn }
    - { role: 07_mysql }
    - { role: 08_app_dev }
