---
- hosts: target_ec2
  user: ec2-user 
  become: yes

  roles:
    - { role: 01_setup }
    - { role: 02_ruby }
    - { role: 03_Bundler }
    - { role: 04_rails }
    - { role: 05_nodejs }
    - { role: 06_yarn }
    - { role: 07_mysql }
    - { role: 08_app_dev }
