--- 
# lec13_CircleCI/.ansible/roles/06_mysql/tasks/main.yml

- name: Check if MariaDB is installed
  command: rpm -q mariadb-server
  register: mariadb_installed
  ignore_errors: yes

- name: Remove MariaDB packages
  yum:
    name: mariadb-server
    state: absent
  when: mariadb_installed.rc == 0


- debug:
    var: rds_endpoint

- name: Install MySQL development package
  yum:
    name: mysql-devel
    state: present
  become: yes

- name: 'Run bundle install'
  shell: bash -lc "bundle install"
  args:
    chdir: "{{ app_dir }}"
  ignore_errors: yes

- name: 'Create database.yml from template'
  template:
    src: database.yml.j2
    dest: "{{ app_dir }}/config/database.yml"
  become: yes
