---
#lec13_CircleCI/.ansible/roles/06_mysql/tasks/main.yml
- name: Check if MariaDB is installed
  command: rpm -q mariadb
  register: mariadb_installed
  ignore_errors: yes

- name: Remove MariaDB packages
  shell: |
    yum remove -y mariadb-*
  when: mariadb_installed.rc == 0


- name: Check if GPG key is imported
  command: rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  register: gpg_key_imported
  ignore_errors: yes

- name: Import GPG key if not imported
  shell: |
    rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  become_user: root
  when: gpg_key_imported.rc != 0


- name: Enable MySQL 5.7 Community repository
  shell: |
    yum-config-manager --enable mysql57-community || true

- name: Install yum-utils
  shell: |
    yum install -y yum-utils
  when: mysql_installed.changed

- name: Update yum cache
  shell: |
    yum makecache
  when: mysql_installed.changed

- name: Install MySQL and dependencies
  shell: |
    yum install -y MySQL-python mysql-devel
  when: mysql_installed.changed

- name: Install MySQL Server
  shell: bash -lc "yum install -y mysql-community-server"
  become_user: root
  when: mysql_installed.changed

- name: Enable MySQL service to start on boot
  shell: bash -lc "systemctl enable mysqld"
  become_user: root
  when: mysql_installed.changed

- name: Create database.yml from template
  template:
    src: database.yml.j2
    dest: "{{ app_dir }}/config/database.yml"
  when: mysql_installed.changed
