---
# tasks/main.yml
- name: Clone the repository
  git:
    repo: 'https://github.com/yuta-ushijima/raisetech-live8-sample-app.git'
    dest: '/home/ec2-user/raisetech-live8-sample-app/'
    force: yes
    
- name: Ensure rbenv directory has correct permissions
  file:
    path: /home/ec2-user/rbenv
    owner: ec2-user
    group: ec2-user
    mode: '0755'
    recurse: yes

- name: Set ownership of the application directory
  file:
    path: /home/ec2-user/raisetech-live8-sample-app
    owner: ec2-user
    group: ec2-user
    recurse: yes

- name: 'yum update'
  yum:
    name: '*'
    state: latest

- name: 'Install required packages'
  yum:
    name: 
      - gcc
      - gcc-c++
      - make
      - openssl-devel
      - libyaml-devel
      - readline-devel
      - zlib-devel
      - libxml2-devel
      - libxslt-devel
      - sqlite-devel
      - libffi-devel
      - ImageMagick
      - ImageMagick-devel
    state: present
