---
- name: Remove MariaDB packages
  yum:
    name: mariadb-*
    state: absent

- name: Install MySQL repository
  yum_repository:
    name: mysql57-community
    description: MySQL 5.7 Community Server
    baseurl: https://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/
    gpgcheck: yes
    gpgkey: https://repo.mysql.com/RPM-GPG-KEY-mysql
    enabled: yes

- name: Install MySQL
  yum:
    name: mysql-community-server
    state: present

- name: Start MySQL service #システム起動時に自動開始
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Get MySQL temporary password  #初回ログイン時のパスワード取得
  command: "grep 'temporary password' /var/log/mysqld.log"
  register: mysql_temp_pass
  changed_when: false
  ignore_errors: yes 

- name: Debug MySQL temporary password
  debug:
    msg: "MySQL temporary password is: {{ mysql_temp_pass.stdout }}"
  when: mysql_temp_pass is defined and mysql_temp_pass.stdout != ''

- name: Log in to MySQL and change root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ lookup('env', 'RDS_PASSWORD') }}"
    login_password: "{{ mysql_temp_pass.stdout }}"
    state: present
  when: mysql_temp_pass is defined and mysql_temp_pass.stdout != ''

- name: Remove anonymous users  #デフォルトで作成される匿名ユーザーの削除
  mysql_user:
    name: ''
    host: localhost
    state: absent

- name: Disallow root login remotely #rootユーザーがリモートからログイン不可にする
  mysql_user:
    name: root
    host: '%'
    state: absent

- name: Remove test database  #デフォルトの「test」というデータベースを削除する
  mysql_db:
    name: test
    state: absent

- name: Flush privileges     # 変更を反映
  command: mysql -u root -p{{ lookup('env', 'RDS_PASSWORD') }} -e "FLUSH PRIVILEGES;"
  when: your_mysql_password is defined
