---
# Bundlerのインストール
- name: Check installed Bundler versions
  command: gem list bundler
  register: installed_bundler_versions_check
  ignore_errors: true

- name: Install Bundler
  command: gem install bundler -v {{ version }}
  when: installed_bundler_versions_check.stdout is not defined or 
        bundler_version not in installed_bundler_versions_check.stdout_lines
