---
- name: Install Bundler
  command: "{{ ansible_env.HOME }}/.rbenv/shims/gem install bundler"
  args:
    chdir: "{{ app_directory }}"

- name: Install gems from Gemfile
  command: "{{ ansible_env.HOME }}/.rbenv/shims/bundle install"
  args:
    chdir: "{{ app_directory }}"