---
- name: Install required development tools
  yum:
    name:
      - gcc
      - make
      - patch
      - readline-devel
      - zlib-devel
      - bzip2-devel
      - libffi-devel
      - openssl-devel
      - libyaml-devel
      - ImageMagick
      - tree
    state: present
