---
- name: Add rbenv to safe directory
  shell: |
    git config --global --add safe.directory /home/ec2-user/.rbenv
  args:
    executable: /bin/bash

- name: Change ownership of .rbenv
  command: chown -R ec2-user:ec2-user /home/ec2-user/.rbenv
  become: true

- name: 'Install rbenv'
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/ec2-user/.rbenv

- name: Add rbenv to PATH
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    state: present

- name: Initialize rbenv in .bash_profile
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
    state: present

- name: Install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
    version: master

- name: Add ruby-build to PATH
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"'
    state: present

- name: Install Ruby with rbenv
  shell: |
    source /home/ec2-user/.bash_profile
    rbenv install 3.2.3
    rbenv global 3.2.3
  args:
    executable: /bin/bash
