---
- name: Install Bundler using rbenv
  shell: |
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    /home/ec2-user/.rbenv/shims/gem install bundler
  args:
    executable: /bin/bash

- name: Bundle install
  command: /home/ec2-user/.rbenv/shims/bundle install
  args:
    chdir: '/home/ec2-user/raisetech-live8-sample-app/'
