---
- name: install nvm
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    creates: /root/.nvm/nvm.sh  # nvmがすでにインストールされている場合はスキップ

- name:  Load nvm environment
  shell: . ~/.nvm/nvm.sh
  args:
    executable: /bin/bash

- name: install Node.js v17.9.1
  shell: |
    . ~/.nvm/nvm.sh
    nvm install 17.9.1
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
