---
- name: Run Yarn installation scripts
  shell: |
    curl -o- -L https://yarnpkg.com/install.sh | bash
  args:
    creates: /usr/local/bin/yarn  # すでにインストールされている場合はスキップ

- name: Load .bashrc and activate Yarn
  shell: source ~/.bashrc
  args:
    executable: /bin/bash

- name: Install Yarn 1.22.19
  shell: |
    source ~/.bashrc
    yarn --version
  register: yarn_version_output
  changed_when: false

