---

- name: Ensure MySQL is started
  ansible.builtin.systemd:
    name: mysqld
    state: started

- name: Run bundle install
  command: /home/ec2-user/rbenv/shims/bundle install
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app

- name: Initialize rbenv
  command: bash -lc "rbenv init -"

- name: Run bin/setup
  command: bash -lc "bin/setup"
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app

- name: Run bin/dev
  command: bin/dev
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app


