---
- name: clone nvm
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ ansible_env.HOME }}/nvm"

- name: Add nvm to .bash_profile
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    line: |
      export NVM_DIR="$HOME/nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    state: present

- name: Reload .bash_profile
  shell: source {{ ansible_env.HOME }}/.bash_profile
  args:
    executable: /bin/bash

- name: Install Node.js 17.9.1 using nvm
  command: "nvm install 17.9.1"
  args:
    executable: /bin/bash
