---
- hosts: targetnode
  gather_facts: false
  vars: 
    app_dir: /home/ec2-user/raisetech-live8-sample-app
    db_host: "{{ lookup('env', 'RDS_ENDPOINT') }}" 
    db_user: "{{ (lookup('env','RDS_ID')) }}"
    db_pw: "{{ (lookup('env','RDS_PASSWORD')) }}"
    S3_bucket: "{{ lookup('env','S3_BUCKET') }}"
    access_key_id: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    secret_access_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    region: "{{ lookup('env','AWS_DEFAULT_REGION') }}"
    
  roles:
    - { role: 01_setup }
    - { role: 02_ruby }
    - { role: 03_rails }
    - { role: 04_nodejs }
    - { role: 05_yarn }
    - { role: 06_mysql }
    - { role: 07_nginx }
    - { role: 08_puma }
    - { role: 09_app_dev }
  