- name: Ensure tmp directory exists with correct permissions
  file:
    path: /home/ec2-user/raisetech-live8-sample-app/tmp
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0775'

- name: Ensure local_secret.txt exists with correct permissions
  file:
    path: /home/ec2-user/raisetech-live8-sample-app/tmp/local_secret.txt
    state: touch
    owner: ec2-user
    group: ec2-user
    mode: '0664'




- name: Run bin/setup in raisetech-live8-sample-app directory
  shell: |
    export RBENV_ROOT="/home/ec2-user/rbenv"
    export PATH="$RBENV_ROOT/bin:$PATH"
    eval "$(rbenv init -)"
    cd /home/ec2-user/raisetech-live8-sample-app
    bin/setup
  args:
    executable: /bin/bash
  become: yes
  become_user: ec2-user


- name: Debug output of bin/setup
  debug:
    var: setup_result

- name: Run bin/dev in raisetech-live8-sample-app directory
  ansible.builtin.command:
    cmd: bin/dev
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app
  register: dev_result

- name: Debug output of bin/dev
  debug:
    var: dev_result
