---
#lec13_CircleCI/.ansible/roles/07_app_dev/tasks/main.yml


- name: Run bundle install
  shell: |
    bash -lc "bundle install"
  args: 
    chdir: "{{ app_dir }}"

#設定ファイルの変更 S3へ
- name: Generate development.rb from template
  template:
    src: development.rb.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/environments/development.rb

- name: Configure S3 settings in storage.yml
  template:
    src: storage.yml.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/storage.yml

#bin/setup
- name: bin/setup
  shell: |
    bash -lc "bin/setup"
  args: 
    chdir: "{{ app_dir }}"

- name: Check if assets are precompiled
  command: test -d "{{ app_dir }}/public/assets" 
  register: assets_check
  ignore_errors: yes

- name: asset precompile
  shell: |
    bash -lc "rails assets:precompile"
  args: 
    chdir: "{{ app_dir }}"

- name: Check if database migration is needed
  command: bash -lc "rails db:version"
  args:
    chdir: "{{ app_dir }}"
  register: migration_check
  ignore_errors: yes

- name: Run database migration
  shell: |
    bash -lc "rails db:migrate"
  args: 
    chdir: "{{ app_dir }}"
  when: migration_check.rc != 0

