---
- name: Ensure MySQL is started
  shell: bash -lc "systemctl start mysqld"

- name: Initialize rbenv
  shell: |
    bash -lc "rbenv init -"
- name: Run bundle install
  shell: bash -lc "cd /home/ec2-user/raisetech-live8-sample-app && /home/ec2-user/.rbenv/shims/bundle install"

- name: Initialize rbenv
  shell: bash -lc "rbenv init -"

- name: Run bin/setup
  shell: bash -lc "cd /home/ec2-user/raisetech-live8-sample-app && bin/setup"
