---
- name: Clone nvm repository
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: /home/ec2-user/nvm
    version: master
    update: no
  become: yes
  become_user: ec2-user
  
- name: Add nvm to .bash_profile
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: |
      export NVM_DIR="$HOME/nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  become: yes
  become_user: ec2-user

- name: Reload .bash_profile
  shell: source /home/ec2-user/.bash_profile
  args:
    executable: /bin/bash
  become: yes
  become_user: ec2-user

- name: Install Node.js 17.9.1 using nvm
  shell: bash -lc "nvm install 17.9.1"
  args:
    executable: /bin/bash
  become: yes
  become_user: ec2-user
