---
- name: Download NVM install script
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Load NVM
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  args:
    executable: /bin/bash

- name: Install Node.js 17.9.1 using NVM
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
    nvm install 17.9.1
  args:
    executable: /bin/bash
