---
- name: Create Puma systemd service file
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  become: yes
  notify: Reload systemd

- name: Start and enable Puma service
  systemd:
    name: puma
    state: started
    enabled: yes
  become: yes
