---
- name: Install NVM
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
    dest: /tmp/nvm_install.sh
    mode: 'u+x'

- name: Run NVM installation script
  shell: /bin/bash /tmp/nvm_install.sh

- name: Load NVM
  shell: . ~/.nvm/nvm.sh
  register: nvm_loaded
  changed_when: false

- name: Install Node.js 17.9.1
  shell: . ~/.nvm/nvm.sh && nvm install 17.9.1

- name: Set Node.js default version
  shell: . ~/.nvm/nvm.sh && nvm alias default 17.9.1
