---
- name: Install NVM
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
    dest: /tmp/nvm_install.sh
    mode: 'u+x'

- name: Run NVM installation script
  shell: /bin/bash /tmp/nvm_install.sh

- name: Load NVM
  shell: . ~/.nvm/nvm.sh
  register: nvm_loaded
  changed_when: false

- name: Add NVM to .bashrc
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'export NVM_DIR="$HOME/.nvm"'
    state: present

- name: Check if Node.js 17.9.1 is already installed
  shell: bash -lc "node --version"
  register: node_installed
  ignore_errors: yes

- name: Install Node.js 17.9.1
  shell: bash -lc "nvm install 17.9.1"
  ignore_errors: yes
  when: node_installed is failed # nodeがインストールされていない場合のみ実行

- name: Run bundle install
  shell: |
    bash -lc "bundle install"
  args: 
    chdir: "{{ app_dir }}"
  ignore_errors: yes

