---
- name: Check if rbenv is installed
  command: rbenv --version
  register: rbenv_installed
  ignore_errors: yes

- name: Clone rbenv if not installed
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: '/home/ec2-user/.rbenv'
  when: rbenv_installed is failed  # rbenvがない場合インストールする

# .bashrcにpathを追加
- name: Add rbenv to PATH in .bashrc
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    state: present

# .bashrcに環境設定を追加
- name: Add rbenv init to .bashrc
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'eval "$(rbenv init -)"'
    state: present
    create: yes

- name: Clone ruby-build if not installed
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: '/home/ec2-user/.rbenv/plugins/ruby-build'

# システム全体でrbenvを使用できるように/etc/profileに変数追加
- name: Insert/update /etc/profile env
  become: yes
  blockinfile:
    path: /etc/profile
    block: |
      export RBENV_ROOT="/home/ec2-user/.rbenv"
      export PATH="${RBENV_ROOT}/bin:${PATH}"
      eval "$(rbenv init --no-rehash -)"

- name: Check if Ruby 3.2.3 is already installed
  shell: bash -lc "ruby -v"
  register: ruby_installed
  ignore_errors: yes

- name: Install Ruby if not already installed
  shell: bash -lc "rbenv install 3.2.3 --no-document"
  when: ruby_installed is failed   # Rubyがインストールされていない場合のみ実行

- name: Set Ruby 3.2.3 as global version
  shell: bash -lc "rbenv global 3.2.3"
  ignore_errors: yes

- name: Check if bundler is installed
  command: /home/ec2-user/.rbenv/shims/gem list bundler -i
  register: bundler_installed
  ignore_errors: yes

- name: Install bundler if not installed
  shell: bash -lc "gem install bundler"
  when: bundler_installed is failed  # bundlerがない場合
  ignore_errors: yes
