---
- name: Ensure .rbenv directory exists
  file:
    path: /home/ec2-user/.rbenv
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/ec2-user/.rbenv
  become: yes
  become_user: ec2-user

- name: Ensure ruby-build directory exists
  file:
    path: /home/ec2-user/.rbenv/plugins/ruby-build
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Download ruby-build repository
  git: 
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build 
  become: yes
  become_user: ec2-user

- name: Add rbenv path to .bashrc
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes

- name: Set rbenv initialization in .bashrc
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'eval "$(rbenv init -)"'
    create: yes



- name: Install Ruby via rbenv
  command: rbenv install {{ ruby_version }}
  args:
    chdir: "{{ app_dir }}"
  become: yes
  become_user: ec2-user

- name: Set global rbenv version
  command: rbenv global {{ ruby_version }}
  args:
    chdir: "{{ app_dir }}"
  become: yes
  become_user: ec2-user
